# Generated by Django 4.0.2 on 2022-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HX2022',
            fields=[
                ('autoid', models.BigAutoField(db_column='Autoid', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=14, null=True)),
                ('udatetime', models.DateTimeField(blank=True, db_column='uDateTime', null=True)),
                ('originalvalue', models.FloatField(blank=True, db_column='OriginalValue', null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('valuestate', models.CharField(blank=True, db_column='ValueState', max_length=100, null=True)),
                ('valuetype', models.SmallIntegerField(blank=True, db_column='ValueType', null=True)),
                ('flag', models.IntegerField(blank=True, db_column='Flag', null=True)),
                ('lastvalue', models.FloatField(blank=True, db_column='LastValue', null=True)),
                ('lasttime', models.DateTimeField(blank=True, db_column='LastTime', null=True)),
            ],
            options={
                'db_table': 'h_x2022',
                'ordering': ['-udatetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='hx2021',
            options={'managed': False, 'ordering': ['-udatetime']},
        ),
    ]
