# Generated by Django 4.0.2 on 2022-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alarmthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmthreshold',
            name='threshold_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
