# Generated by Django 4.0.2 on 2022-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_alter_hx2022_udatetime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hx2022',
            index=models.Index(fields=['code'], name='h_x2022_Code_48f25a_idx'),
        ),
        migrations.AddIndex(
            model_name='hx2022',
            index=models.Index(fields=['udatetime'], name='h_x2022_uDateTi_29c469_idx'),
        ),
    ]
