# Generated by Django 4.0.2 on 2022-04-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_hx2022_h_x2022_code_48f25a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usensor',
            options={'managed': False, 'ordering': ['-sensortypename']},
        ),
    ]
