# Generated by Django 4.0.2 on 2022-04-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alarmthreshold_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='is_access',
            field=models.BooleanField(default=False),
        ),
    ]
