# Generated by Django 4.0.2 on 2022-04-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_alter_alarmthreshold_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmthreshold',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
