# Generated by Django 4.0.2 on 2022-05-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_alter_alarmthreshold_threshold_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alarmthreshold',
            constraint=models.UniqueConstraint(fields=('user', 'sensor'), name='unique_threshold'),
        ),
    ]
