# Generated by Django 4.0.2 on 2022-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_alarmthreshold_unique_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmthreshold',
            old_name='threshold_value',
            new_name='threshold_value_max',
        ),
        migrations.AddField(
            model_name='alarmthreshold',
            name='threshold_value_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
