# Generated by Django 4.0.2 on 2022-04-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_alter_userextend_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usensor',
            options={'managed': True, 'ordering': ['-sensortypename']},
        ),
    ]
